#pragma config(Sensor, dgtl2,  LeftSensor,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  MidSensor,      sensorDigitalIn)
#pragma config(Sensor, dgtl10, AutoCheck,      sensorTouch)
#pragma config(Sensor, dgtl12, RightSensor,    sensorDigitalIn)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           wrist,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           condAct,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           pushRod,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long L;
long R;
float MaxSpeed = 0.3;
float MinSpeed = -0.3;
float LeftSpeed = 0.0;
float RightSpeed = 0.0;
float increment = 0.05;
bool pathFinished = false;

bool sensorCheck(long sens) {
    return (sens < 0.5);
}
float MotorCheck(float speed, float min, float max, float change) {
   speed += change;
   if (speed > max) {
       speed = max;
   } else if (speed < min) {
       speed = min;
   }
   return speed;
}

void auto() {
	if (sensorCheck(SensorValue[AutoCheck])) {
		pathFinished = true;
		motor[left] = 0;
		motor[right] = 0;
		//Change to default main switch case here
	} else {
		if (sensorCheck(L) && sensorCheck(R)) {		// If both are detecting white
	  	LeftSpeed = MotorCheck(LeftSpeed, MinSpeed, MaxSpeed, increment);
	  	RightSpeed = MotorCheck(RightSpeed, MinSpeed, MaxSpeed, increment);
	  } else if (sensorCheck(L) && !sensorCheck(R)){	// If only left is detcting white
	  	LeftSpeed = MotorCheck(LeftSpeed, MinSpeed, MaxSpeed, -increment);
	  	RightSpeed = MotorCheck(RightSpeed, MinSpeed, MaxSpeed, increment);
	  } else if (!sensorCheck(L) && sensorCheck(R)){	// If only right is detecting white
	  	LeftSpeed = MotorCheck(LeftSpeed, MinSpeed, MaxSpeed, increment);
	  	RightSpeed = MotorCheck(RightSpeed, MinSpeed, MaxSpeed, -increment);
	  } else {		// If neither are detecting white
	  	LeftSpeed = MotorCheck(LeftSpeed, MinSpeed, MaxSpeed, -increment);
	  	RightSpeed = MotorCheck(RightSpeed, MinSpeed, MaxSpeed, -increment);
		}
		motor[left] = LeftSpeed * 127;
		motor[right] = RightSpeed * 127;
	}
}
task main () {

}
