#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           rake,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           pushRod,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int motorVal;

bool incBtnPressed=false;
bool decBtnPressed=false;


// Program to PRINTOUT and ADJUST the speed of motor that should be slower/faster to keep robot moving in straight line


// Example usage of debug stream print to console
		// writeDebugStream("int x is: %d", x);  // writes the current value of int 'x' to the debug stream


void printMotorValue() {
	writeDebugStreamLine("\nCurrent motor/servo value = %4d", motorVal);
}


task main()
{
	while(true) {
		if (vexRT[Btn8U] && !incBtnPressed) {				// UP btn on RIGHT gamepad to INCREMENT by 1
			motorVal++;
			printMotorValue();

			incBtnPressed = true;
		} else if (!vexRT[Btn8U]) {
			incBtnPressed = false;
		}
		if (vexRT[Btn8D] && !decBtnPressed) {				// DOWN btn on RIGHT gamepad to DECREMENT by 1
			motorVal--;
			printMotorValue();

			decBtnPressed = true;
		} else if (!vexRT[Btn8D]) {
			decBtnPressed = false;
		}
		motor[left] = motorVal;																						// change LEFT to motor needing of adjusting
	}
}
