#pragma config(Sensor, in2,    elbowPotSensor, sensorPotentiometer)
#pragma config(Sensor, dgtl2,  LeftSensor,     sensorDigitalIn)
#pragma config(Sensor, dgtl10, AutoCheck,      sensorTouch)
#pragma config(Sensor, dgtl12, RightSensor,    sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



// Program to PRINTOUT the value of a sensor

int gendigSens;
unsigned char touchSens;				// sens range (0 OR 1)
short sonarSens;								// sens range (0 TO 255)
short quadencodeSens;						// sens range (-32,786 TO 32,768)
unsigned short lightSens;				// sens range (0 TO 4095)
unsigned short potSens;					// sens range (0 TO 4095)
unsigned short linefollowSens;	// sens range (0 TO 4095)
short gyroSens;									// sens range (-3600 TO 3600)
unsigned short accelSens;				// sens range (0 TO 4095)

task main()
{
	while(true) {
		// genericDigital sensor
				//gendigSens = SensorValue[GENERIC_DIGITALsens];

		// touch sensor
				//touchSens = SensorValue[TOUCHsensor];

		// sonar sensor
				//sonarSns = SensorValue[SONARsensor];

		// quadratureEncoder sensor
				//quadencodeSens = SensorValue[QUADRATURE_ENCODERsensor];

		// light sensor
				//lightSens = SensorValue[LIGHTsensor];

		// potentiometer sensor
				//potSens = SensorValue[POTENTIOMETERsensor];

		// lineFollower sensor
				//linefollowSens = SensorValue[LINE_FOLLOWERsensor];

		// gyro sensor
				//gyroSens = SensorValue[GYROsensor];

		// accelerometer sensor
				//accelSens = SensorValue[ACCELEROMETERsens];

		// print out sensor value
		writeDebugStreamLine(
		"Sensor value at %d seconds = %4d",
		nSysTime, gendigSens);																				// change gendigSens to sensor value for input sensor of SensorValue[]

		wait1Msec(1000);																									// change 1000 to amount of ms needed between printouts (1000ms = 1sec)
	}
}
